version: '3.7'

services:
  php:
    build:
      context: .
      target: build_php_dev
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/app
    environment:
      XDEBUG_CONFIG: >-
        remote_enable=1
        remote_connect_back=1
        remote_port=9001
        idekey=PHPSTORM
    networks:
      - ddstack

  apache:
    volumes:
      - ./:/app
    networks:
      - ddstack
      - traefik
    ports:
      - 8090:80
    labels:
      - "traefik.enable=true"
      - "traefik.backend=${COMPOSE_PROJECT_NAME}"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.traefik.docker"
      - "traefik.port=80"

  mariadb:
    networks:
      - ddstack
    ports:
      - 3306:3306

networks:
  traefik:
    external:
      name: traefik
  ddstack:
    external:
      name: ddstack
